apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-z60m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-z60m
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-z60m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-z60m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-z60m
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dpnt-tenant/rhtap-demo-app/hacbs-test-project-z60m@sha256:675f0d5fd0390a015d11c138607b19b33b66814330a055c03ce66a3da5121562
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
